<header>
    <div class="content">
        <h1><a href="/">HexDump - Online hex viewer</a></h1>
        <a href="#" class="button">Convert</a>
    </div>
</header>
<div id="body">
    <form action="/convert" method="post" enctype="multipart/form-data" id="convertform">
        <h2>Upload file</h2>
        <input type="file" name="file">
        <h2>Direct input</h2>
        <textarea name="string"></textarea>
    </form>
</div>
